version: '3.8'

services:
  db:
    container_name: test_postgres
    restart: always
    image: "postgres:15-alpine"
    environment:
      POSTGRES_PASSWORD: fastapi_traefik
      POSTGRES_USER: fastapi_traefik
      POSTGRES_DB: fastapi_traefik
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432

  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
      - DB_HOST=test_postgres                 # Database hostname      
      - DD_AGENT_HOST=datadog        # Datadog Agent hostname (matches your datadog service name)
    depends_on:
      - db
    extra_hosts:                             # Linux only configuration
      - "host.docker.internal:host-gateway"  # Linux only configuration
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  traefik:
    image: traefik:v2.9.6
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  datadog:
    container_name: dd-agent
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      - DD_API_KEY=9bef7693c3fee1874ac793162d7ac55c
      - DD_SITE=datadoghq.eu
      - DD_APM_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_PROCFS_PATH=/proc  
      # Optionally enable logs and process monitoring:
      # - DD_LOGS_ENABLED=true
      # - DD_PROCESS_AGENT_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: unless-stopped

volumes:
  postgres_data:
